[package]
name = "flightstream-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
xplane-sdk-sys = { version = "*", features = ["generate-bindings"] }
xplm = "0.4.2"

[lib]
crate-type = ["cdylib"]
